version: '3.4'

services:
  webapi:
    container_name: webapi
    image: ${DOCKER_REGISTRY-}folklibrarywebapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    volumes:
    - /d/music/folk:/app/data
    depends_on:
    - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: folklibrary
    volumes:
       - ./_postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    depends_on:
    - postgres

