version: '3.4'

services:
  folklibrary.webapi:
    container_name: WebApi
    image: ${DOCKER_REGISTRY-}folklibrarywebapi
    build:
      context: .
      dockerfile: FolkLibrary.WebApi/Dockerfile
    volumes:
    - /d/music/folk:/app/data
    - ./rabbitmq/definitions.json:/app/rabbitmq_definitions.json
    depends_on:
    - postgres
    - mongodb
    - rabbitmq
  folklibrary.functions:
    container_name: Functions
    image: ${DOCKER_REGISTRY-}folklibraryfunctions
    build:
      context: .
      dockerfile: FolkLibrary.Functions/Dockerfile
    depends_on:
    - postgres
    - mongodb
    - rabbitmq
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management
    ports:
    - 15672:15672
    volumes:
    - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    environment:
    - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
  postgres:
    container_name: Postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: folklibrary
  postgres.admin:
    container_name: Postgres.Admin
    image: dbeaver/cloudbeaver
    ports:
    - 8978:8978
    depends_on:
    - postgres
  mongodb:
    container_name: MongoDB
    image: mongo
  mongodb.admin:
    container_name: MongoDB.Admin
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
    - mongodb

