version: '3.4'

services:
  # webapi:
  #   container_name: webapi
  #   image: ${DOCKER_REGISTRY-}folklibrarywebapi
  #   build:
  #     context: .
  #     dockerfile: WebApi/Dockerfile
  #   volumes:
  #   - /d/music/folk:/app/data
  #   depends_on:
  #   - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: folklibrary
  postgres.admin:
    container_name: postgres.admin
    image: dbeaver/cloudbeaver
    ports:
    - 8978:8978
    depends_on:
    - postgres

