version: '3.4'

services:
  webapi:
    container_name: webapi
    image: ${DOCKER_REGISTRY-}folklibrarywebapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    volumes:
    - /d/music/folk:/app/data
    depends_on:
    - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: folklibrary
    volumes:
       - ./docker_local/postgresql/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - 5433:80
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: False
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: False
    volumes:
      - ./docker_local/pgadmin:/var/lib/pgadmin
    depends_on:
    - postgres

